routes/web.php
<?php

use App\Http\Controllers\WelcomeController;
use App\Http\Controllers\Auth\NewPasswordController;
use App\Http\Controllers\Auth\PasswordResetLinkController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', [WelcomeController::class, 'index'])
    ->middleware('guest')
    ->name('welcome');
Route::post('/register', [WelcomeController::class, 'store'])
    ->middleware('guest')
    ->name('register');

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::resource('dropdown', \DropdownController::class);




Route::get('/forgot-password', [PasswordResetLinkController::class, 'create'])
    ->middleware('guest')
    ->name('password.request');

Route::post('/forgot-password', [PasswordResetLinkController::class, 'store'])
    ->middleware('guest')
    ->name('password.email');

Route::get('/reset-password/{token}', [NewPasswordController::class, 'create'])
    ->middleware('guest')
    ->name('password.reset');

Route::post('/reset-password', [NewPasswordController::class, 'store'])
    ->middleware('guest')
    ->name('password.update');






Route::middleware('permission')->prefix('hr')->group(function () {
    Route::resource('staffs', 'StaffController')->except('destroy');
    Route::post('/staff-status-update', 'StaffController@status_update')->name('staffs.update_active_status');
    Route::get('/staff/view/{id}', 'StaffController@show')->name('staffs.view');
    Route::get('/staff/report-print/{id}', 'StaffController@report_print')->name('staffs.report_print');
    Route::get('/staff/destroy/{id}', 'StaffController@destroy')->name('staffs.destroy');
});


Route::post('/staff-document/store', 'StaffController@document_store')->name('staff_document.store');
Route::get('/staff-document/destroy/{id}', 'StaffController@document_destroy')->name('staff_document.destroy');
Route::get('/profile-view', 'StaffController@profile_view')->name('profile_view');
Route::post('/profile-edit', 'StaffController@profile_edit')->name('profile_edit_modal');
Route::post('/profile-update/{id}', 'StaffController@profile_update')->name('profile.update');





Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/advance/search', 'AdvanceSearchController@index')->name('advance/search');
    Route::get('/bare_acts', 'BareActsController@index')->name('bare_acts');
    Route::get('/archive', 'ArchiveController@index')->name('archive');
    Route::get('/display_board', 'DisplayboardController@index')->name('display_board');
    Route::get('/court_fee_cal', 'CourtFeeController@index')->name('court_fee_cal');
    Route::get('/connected_matters', 'ConnectedMatersController@index')->name('connected_matters');
    Route::get('/my_client', 'MyclientController@index')->name('my_client');
    Route::get('case/active', 'CaseController@indexx')->name('case.active');
    Route::get('court_list', 'CourtListController@index')->name('court_list');
    Route::get('calculation', 'CalculationController@index')->name('calculation');
    Route::get('calculation_of_int', 'CalculationOfInterestController@index')->name('calculation_of_int');
    Route::get('ocr', 'OcrController@index')->name('ocr');
    Route::get('case/today', 'CaseController@indexxx')->name('case.today');
    Route::get('case/tomorrow', 'CaseController@indexxxx')->name('case.tomorrow');
    Route::get('case/dailyboard/{date?}', 'CaseController@indexxxxx')->name('case.dailyboard');
    Route::get('case/dateawaited', 'CaseController@indexxxxxx')->name('case.dateawaited');
    Route::post('case/update', 'CaseController@update')->name('case.update');

    Route::any('case/category/change/{id}', 'CaseController@category_change')->name('case.category.change');
    Route::any('case/category/store', 'CaseController@category_store')->name('case.category.store');

    Route::any('case/court/change/{id}', 'CaseController@court_change')->name('case.court.change');
    Route::any('case/court/store', 'CaseController@court_store')->name('case.court.store');

    Route::get('my-profile', 'StaffController@profile_view')->name('my-profile');
    Route::get('add-lawyer/{case}', 'CaseController@add_lawyer')->name('case.add_lawyer');
    Route::post('add-lawyer/{case}', 'CaseController@post_lawyer');
    Route::delete('remove-lawyer/{case}/{lawyer}', 'CaseController@remove_lawyer')->name('case.remove_lawyer');
    Route::post('update/next_date', 'CaseController@update_next_date')->name('update.next_date');

    Route::get('case_delete/{id}', 'CaseController@case_delete')->name('case.delete');

    Route::group(['middleware' => 'permission'], function () {

        Route::group(['prefix' => 'master', 'as' => 'master.', 'namespace' => 'Master'], function () {
            Route::resource('stage', 'StageController');
            Route::resource('act', 'ActController');
            Route::resource('court', 'CourtController');
        });


        Route::group(['prefix' => 'category', 'as' => 'category.', 'namespace' => 'Category'], function () {
            Route::resource('court', 'CourtController');
            Route::resource('case', 'CaseController');
            Route::resource('client', 'ClientController');
            Route::resource('contact', 'ContactController');
        });




        Route::resource('lawyer', 'LawyerController');

        Route::resource('contact', 'ContactController');

        Route::resource('client', 'ClientController');
        Route::get('case/filter', 'CaseController@filter')->name('case.filter');


        Route::resource('case', 'CaseController');

        Route::get('date/send_mail', 'HearingDateController@send_mail')->name('date.send_mail');
        Route::post('date/send_mail', 'HearingDateController@post_send_mail');
        Route::resource('date', 'HearingDateController');
        Route::resource('putlist', 'PutlistController');
        Route::resource('lobbying', 'LobbyingController');


        Route::any('judgement/reopen', 'JudgementController@reopen')->name('judgement.reopen');
        Route::any('judgement/close', 'JudgementController@close')->name('judgement.close');

        Route::get('/causelist', 'CaseController@causelist')->name('causelist.index');

        Route::any('closed', 'JudgementController@closed')->name('judgement.closed');

        Route::resource('judgement', 'JudgementController');

        Route::resource('appointment', 'AppointmentController');

        Route::any('judgement/reopen/store', 'JudgementController@reopen_store')->name('judgement.reopen_store');
        Route::any('judgement/close/store', 'JudgementController@close_store')->name('judgement.close_store');


        Route::get('/updateSystem', 'UpdateController@updatesystem')->name('setting.updatesystem');
        Route::post('/updateSystem', 'UpdateController@updatesystemsubmit')->name('setting.updateSystem.submit1');

        Route::group(['prefix' => 'setup', 'as' => 'setup.'], function () {
            Route::resource('country', 'CountryController');
            Route::resource('state', 'StateController');
            Route::resource('city', 'CityController');
        });

        Route::post('add/client', 'ClientController@store')->name('add.client');

        Route::post('add/organization', 'OrganizationController@store')->name('add.organization');
        Route::post('add/referance', 'OrganizationController@ref_store')->name('add.referance');

        Route::post('custom/district', 'CityController@custom_district')->name('custom_district');
        Route::post('custom/bench', 'CityController@bench')->name('bench');
        Route::post('custom/case_type', 'CityController@case_type')->name('case_type');

    });



    Route::get('/change-password', 'HomeController@change_password')->name('change_password');
    Route::post('/change-password', 'HomeController@post_change_password');

    Route::post('/search', 'SearchController@search')->name('search');

    Route::resource('file', 'FileController');
});


Route::any('date-reminder-corn', 'DateRemainderController@dueDate')->name('date-reminder');

Route::group(['as' => 'select.', 'prefix' => 'select'], function () {
    Route::get('/division', 'Api\SelectController@division')->name('division');
    Route::post('/state', 'Api\SelectController@state')->name('state');
    Route::post('/city', 'Api\SelectController@city')->name('city');
    Route::post('/court', 'Api\SelectController@court')->name('court');
});



Route::get('/js/lang/js', function () {

    //    if (\App::environment('local')) {
    \Cache::forget('jslang.js');
    //    }

    if (\Cache::has('locale')) {
        config(['app.locale' => \Cache::get('locale')]);
    }

    $strings = Cache::rememberForever('jslang.js', function () {
        $lang = config('app.locale');

        $file   = resource_path('lang/' . $lang . '/js.php');
        $strings = [];
        if (\Illuminate\Support\Facades\File::exists($file)) {
            $name           = basename($file, '.php');
            $strings[$name] = require $file;
        }

        //        Remove this if block if you dont need to load language insides module

        if (class_exists(\Nwidart\Modules\Module::class)) {
            $modules = \Module::all();
            $module_files = [];
            foreach ($modules as $module) {
                if ($module->isEnabled()) {
                    $file = module_path($module->getName()) . '/Resources/lang/' . $lang . '/js.php';

app/Http/Controllers/Category/CourtController.php
<?php

namespace App\Http\Controllers\Category;

use App\Http\Controllers\Controller;
use App\Models\CourtCategory;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Validation\ValidationException;

class CourtController extends Controller {
	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index() {
		$models = CourtCategory::with('courts')->get();
		return view('category.court.index', compact('models'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create() {

        $quick_add = request()->quick_add;
        if (request()->ajax() and $quick_add == 1){
            return view('category.court.create_modal');
        }
		return view('category.court.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return void
	 * @throws ValidationException
	 */
	public function store(Request $request) {
		if (!$request->json()) {
			abort(404);
		}
        $validate_rules = [
            'name' => 'required|max:191|string',
            'description' => 'sometimes|nullable|max:1500|string',
        ];


        $request->validate($validate_rules, validationMessage($validate_rules));

		$model = new CourtCategory();
		$model->name = $request->name;
		$model->description = $request->description;
		$model->save();

		$response = [
			'model' => $model,
			'message' => __('court.Court Category Added Successfully'),
		];

        if ($request->quick_add == 1){
            $response['appendTo'] = '#court_category_id';
        }

		return response()->json($response);
	}

	/**
	 * Display the specified resource.
	 *
	 * @param int $id
	 * @return Response
	 */
	public function show($id) {
		$model = CourtCategory::findOrFail($id);
		return view('category.court.show', compact('model'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param int $id
	 * @return Response
	 */
	public function edit($id) {
		$model = CourtCategory::findOrFail($id);
		return view('category.court.edit', compact('model'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param Request $request
	 * @param int $id
	 * @return Response
	 * @throws ValidationException
	 */
	public function update(Request $request, $id) {
		if (!$request->json()) {
			abort(404);
		}

        $validate_rules = [
            'name' => 'required|max:191|string',
            'description' => 'sometimes|nullable|max:1500|string',
        ];

        $request->validate($validate_rules, validationMessage($validate_rules));

		$model = CourtCategory::find($id);
		if (!$model) {
			throw ValidationException::withMessages(['message' => __('court.Court Category Not Found')]);
		}

		$model->name = $request->name;
		$model->description = $request->description;
		$model->save();

		$response = [
			'message' => __('court.Court Category Updated Successfully'),
			'goto' => route('category.court.index'),
		];

		return response()->json($response);
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param Request $request
	 * @param int $id
	 * @return void
	 * @throws ValidationException
	 */
	public function destroy(Request $request, $id) {
		if (!$request->json()) {
			abort(404);
		}

		$model = CourtCategory::with('courts')->find($id);
		if (!$model) {
			throw ValidationException::withMessages(['message' => __('court.Court Category Not Found')]);
		}
		if ($model->courts->count()) {
			throw ValidationException::withMessages(['message' => __('court.Court Category Assign To Court.')]);
		}
		$model->delete();

		return response()->json(['message' => __('court.Court Category Deleted Successfully'), 'goto' => route('category.court.index')]);
	}
}

app/Http/Controllers/Master/ActController.php
<?php

namespace App\Http\Controllers\Master;

use App\Http\Controllers\Controller;
use App\Models\Act;
use Illuminate\Http\Request;
use Illuminate\Validation\ValidationException;

class ActController extends Controller {
	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index() {
		$models = Act::all();
		return view('master.act.index', compact('models'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create() {
        $quick_add = request()->quick_add;
        if (request()->ajax() and $quick_add == 1){
            return view('master.act.create_modal');
        }
		return view('master.act.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return void
	 * @throws ValidationException
	 */
	public function store(Request $request) {
		if (!$request->json()) {
			abort(404);
		}
        $validate_rules = [
            'name' => 'required|max:191|string',
            'description' => 'sometimes|nullable|max:1500|string',
        ];

        $request->validate($validate_rules, validationMessage($validate_rules));

		$model = new Act();
		$model->name = $request->name;
		$model->description = $request->description;
		$model->save();

		$response = [
			'model' => $model,
			'message' => __('case.Act Added Successfully'),
		];

        if ($request->quick_add == 1){
            $response['appendTo'] = '#acts';
        }

        return response()->json($response);
	}

	/**
	 * Display the specified resource.
	 *
	 * @param int $id
	 * @return Response
	 */
	public function show($id) {
		$model = Act::findOrFail($id);
		return view('master.act.show', compact('model'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param int $id
	 * @return Response
	 */
	public function edit($id) {
		$model = Act::findOrFail($id);
		return view('master.act.edit', compact('model'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param Request $request
	 * @param int $id
	 * @return Response
	 * @throws ValidationException
	 */
	public function update(Request $request, $id) {
		if (!$request->json()) {
			abort(404);
		}

        $validate_rules = [
            'name' => 'required|max:191|string',
            'description' => 'sometimes|nullable|max:1500|string',
        ];

        $request->validate($validate_rules, validationMessage($validate_rules));

		$model = Act::find($id);
		if (!$model) {
			throw ValidationException::withMessages(['message' => __('case.Act Not Found')]);
		}

		$model->name = $request->name;
		$model->description = $request->description;
		$model->save();

		$response = [
			'message' => __('case.Act Updated Successfully'),
			'goto' => route('master.act.index'),
		];

		return response()->json($response);
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param Request $request
	 * @param int $id
	 * @return void
	 * @throws ValidationException
	 */
	public function destroy(Request $request, $id) {
		if (!$request->json()) {
			abort(404);
		}

		$model = Act::find($id);
		if (!$model) {
			throw ValidationException::withMessages(['message' => __('case.Act Not Found')]);
		}

		//Check Client

		$model->delete();

		return response()->json(['message' => __('case.Act Deleted Successfully'), 'goto' => route('master.act.index')]);
	}
}

resources/views/master/court/create.blade.php
@extends('layouts.master', ['title' => __('court.Create New Court')])

@section('mainContent')

    <section class="admin-visitor-area up_st_admin_visitor">
        <div class="container-fluid p-0">
            <div class="row justify-content-center">
                <div class="col-12">
                    <div class="box_header">
                        <div class="main-title d-flex justify-content-between w-100">
                            <h3 class="mb-0 mr-30">{{ __('court.New Court') }}</h3>

                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <div class="white_box_50px box_shadow_white">


                        {!! Form::open(['route' => 'master.court.store', 'class' => 'form-validate-jquery', 'id' => 'content_form', 'files' => false, 'method' => 'POST']) !!}
                        <div class="row">
                            <div class="primary_input col-md-4">
                                {{Form::label('country_id', __('court.Country'))}}
                                {{Form::select('country_id', $countries, config('configs')->where('key','country_id')->first()->value, ['class' => 'primary_select', 'id' => 'country_id', 'data-placeholder' => __('court.Select country'),  'data-parsley-errors-container' => '#country_id_error'])}}
                                <span id="country_id_error"></span>
                            </div>

                            <div class="primary_input col-md-4">
                                {{Form::label('state_id', __('court.State'))}}
                                {{Form::select('state_id', $states, null, ['class' => 'primary_select','id' => 'state_id', 'data-placeholder' => __('court.Select state'), 'data-parsley-errors-container' => '#state_id_error'])}}
                                <span id="state_id_error"></span>
                            </div>

                            <div class="primary_input col-md-4">
                                {{Form::label('city_id', __('court.City'))}}
                                {{Form::select('city_id',[''=> __('common.Select State First')], null, ['class' => 'primary_select','id' => 'city_id', 'data-placeholder' => __('court.Select city'), 'data-parsley-errors-container' => '#city_id_error'])}}
                                <span id="city_id_error"></span>
                            </div>

                        </div>
                        <div class="row">

                            <div class="primary_input col-md-6">

                                <div class="d-flex justify-content-between">
                                    {{Form::label('court_category_id', __('court.Court Category'), ['class' => 'required'])}}
                                    @if(permissionCheck('category.court.store'))
                                        <label class="primary_input_label green_input_label" for="">
                                            <a href="{{ route('category.court.create', ['quick_add' => true]) }}"
                                               class="btn-modal"
                                               data-container="court_category_add_modal">{{ __('case.Create New') }}
                                                <i class="fas fa-plus-circle"></i></a></label>
                                    @endif
                                </div>
                                {{Form::select('court_category_id', $court_categories, null, ['class' => 'primary_select', 'data-placeholder' => __('court.Court Category'), 'data-parsley-errors-container' => '#court_category_error', 'required'])}}
                                <span id="court_category_error"></span>
                            </div>
                            <div class="primary_input col-md-6">
                                {{Form::label('location', __('court.Location/ Police Station'))}}
                                {{Form::text('location', null, ['class' => 'primary_input_field', 'placeholder' => __('court.Location/ Police Station')])}}
                            </div>
                        </div>
                        <div class="row">
                            <div class="primary_input col-md-6">
                                {{Form::label('name', __('court.Court Name'),['class' => 'required'])}}
                                {{Form::text('name', null, ['required' => '', 'class' => 'primary_input_field', 'placeholder' => __('court.Court Name')])}}
                            </div>
                            <div class="primary_input col-md-6">
                                {{Form::label('room_number', __('court.Court Room Number'))}}
                                {{Form::text('room_number', null, ['class' => 'primary_input_field', 'placeholder' => __('court.Court Room Number')])}}
                            </div>
                        </div>
                        @if(moduleStatusCheck('EmailtoCL'))
                            <div class="row">

                                <div class="primary_input col-12">
                                    {{Form::label('email', __('case.Email'))}}
                                    {{Form::email('email', null, ['class' => 'primary_input_field', 'placeholder' => __('case.Email')])}}
                                </div>

                            </div>
                        @endif
                        @includeIf('customfield::fields', ['fields' => $fields, 'model' => null])
                        <div class="primary_input">
                            {{Form::label('description', __('court.Description'))}}
                            {{Form::textarea('description', null, ['class' => 'primary_input_field summernote', 'placeholder' => __('court.Court  Description'), 'rows' => 5, 'maxlength' => 1500, 'data-parsley-errors-container' =>
                            '#description_error' ])}}
                            <span id="description_error"></span>
                        </div>

                        <div class="text-center mt-3">
                            <button class="primary-btn semi_large2 fix-gr-bg submit" type="submit"><i
                                    class="ti-check"></i>{{ __('common.Create') }}
                            </button>

                            <button class="primary-btn semi_large2 fix-gr-bg submitting" type="submit" disabled
                                    style="display: none;"><i class="ti-check"></i>{{ __('common.Creating') . '...' }}
                            </button>

                        </div>
                        {!! Form::close() !!}


                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="modal fade animated court_category_add_modal infix_advocate_modal" id="remote_modal" tabindex="-1"
         role="dialog"
         aria-labelledby="remote_modal_label" aria-hidden="true" data-backdrop="static">
    </div>


@stop
@push('admin.scripts')
    <script>
        $(document).ready(function () {
            _componentAjaxChildLoad('#content_form', '#country_id', '#state_id', 'state')
            _componentAjaxChildLoad('#content_form', '#state_id', '#city_id', 'city')
            _formValidation();
        });
    </script>
@endpush

resources/views/master/court/index.blade.php
@extends('layouts.master', ['title' => __('court.Court')])

@section('mainContent')

    <section class="admin-visitor-area up_st_admin_visitor">
        <div class="container-fluid p-0">
            <div class="row justify-content-center">
                <div class="col-12">
                    <div class="box_header common_table_header xs_mb_0">
                        <div class="main-title d-md-flex">
                            <h3 class="mb-0 mr-30 mb_xs_15px mb_sm_20px">{{ __('court.Court List') }}</h3>
                            <ul class="d-flex">
                                @if(permissionCheck('master.court.store'))
                                    <li><a class="primary-btn radius_30px mr-10 fix-gr-bg"
                                           href="{{ route('master.court.create') }}"><i class="ti-plus"></i>{{ __
                        ('court.New Court') }}</a></li>
                                @endif
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="QA_section QA_section_heading_custom check_box_table">
                        <div class="QA_table ">
                            <!-- table-responsive -->
                            <div class="">
                                <table class="table Crm_table_active3">
                                    <thead>
                                    <tr>

                                        <th scope="col">{{ __('court.SL') }}</th>
                                        <th>{{ __('court.Category') }}</th>
                                        <th>{{ __('court.Court') }}</th>
                                        @if(moduleStatusCheck('EmailtoCL'))
                                            <th>{{ __('case.Email') }}</th>
                                        @endif
                                        <th>{{ __('court.Location') }}</th>
                                        <th>{{ __('court.Actions') }}</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($models as $model)
                                        <tr>

                                            <td>{{ $loop->index + 1 }}</td>
                                            <td>
                                                @if($model->court_category)
                                                    <a href="{{ route('category.court.show', $model->court_category->id) }}"> {{ $model->court_category->name }} </a>
                                                @else
                                                    <span class="badge_4">{{ __('court.No Category') }}</span>
                                                @endif
                                            </td>
                                            <td>
                                                <a href="{{ route('master.court.show', $model->id) }}">{{ $model->name }} {{ $model->room_number ? ' ('.$model->room_number .')' : '' }}</a>
                                            </td>
                                            @if(moduleStatusCheck('EmailtoCL'))
                                                <td>{{ $model->email }}</td>
                                            @endif
                                            <td>
                                                {{ $model->state ? $model->state->name .', ' : '' }}
                                                {{ $model->city ? $model->city->name .', ' : ''}}
                                                {{ $model->location }}
                                            </td>

                                            <td>


                                                <div class="dropdown CRM_dropdown">
                                                    <button class="btn btn-secondary dropdown-toggle" type="button"
                                                            id="dropdownMenu2" data-toggle="dropdown"
                                                            aria-haspopup="true"
                                                            aria-expanded="false">
                                                        {{ __('common.Select') }}
                                                    </button>
                                                    <div class="dropdown-menu dropdown-menu-right"
                                                         aria-labelledby="dropdownMenu2">
                                                        @if(permissionCheck('master.court.show'))
                                                            <a href="{{ route('master.court.show', $model->id) }}"
                                                               class="dropdown-item"><i class="icon-file-eye"></i> {{ __
                                                        ('common.View') }}</a>
                                                        @endif
                                                        @if(permissionCheck('master.court.edit'))
                                                            <a href="{{ route('master.court.edit', $model->id) }}"
                                                               class="dropdown-item"><i
                                                                    class="icon-pencil"></i> {{ __('common.Edit') }}</a>
                                                        @endif
                                                        @if(permissionCheck('master.court.destroy'))
                                                            <span id="delete_item" data-id="{{ $model->id }}" data-url="{{ route
                                                            ('master.court.destroy', $model->id)
                                                        }}" class="dropdown-item"><i class="icon-trash"></i> {{ __('common.Delete') }} </span>
                                                        @endif

                                                    </div>
                                                </div>


                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>

@stop
@push('admin.scripts')

    <script>
        $(document).ready(function () {

        });
    </script>
@endpush