routes/web.php
Route::get('/', [WelcomeController::class, 'index'])
    ->middleware('guest')
    ->name('welcome');
Route::post('/register', [WelcomeController::class, 'store'])
    ->middleware('guest')
    ->name('register');

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::resource('dropdown', \DropdownController::class);




Route::get('/forgot-password', [PasswordResetLinkController::class, 'create'])
    ->middleware('guest')
    ->name('password.request');

Route::post('/forgot-password', [PasswordResetLinkController::class, 'store'])
    ->middleware('guest')
    ->name('password.email');

Route::get('/reset-password/{token}', [NewPasswordController::class, 'create'])
    ->middleware('guest')
    ->name('password.reset');

Route::post('/reset-password', [NewPasswordController::class, 'store'])
    ->middleware('guest')
    ->name('password.update');






Route::middleware('permission')->prefix('hr')->group(function () {
    Route::resource('staffs', 'StaffController')->except('destroy');
    Route::post('/staff-status-update', 'StaffController@status_update')->name('staffs.update_active_status');
    Route::get('/staff/view/{id}', 'StaffController@show')->name('staffs.view');
    Route::get('/staff/report-print/{id}', 'StaffController@report_print')->name('staffs.report_print');
    Route::get('/staff/destroy/{id}', 'StaffController@destroy')->name('staffs.destroy');
});


Route::post('/staff-document/store', 'StaffController@document_store')->name('staff_document.store');
Route::get('/staff-document/destroy/{id}', 'StaffController@document_destroy')->name('staff_document.destroy');
Route::get('/profile-view', 'StaffController@profile_view')->name('profile_view');
Route::post('/profile-edit', 'StaffController@profile_edit')->name('profile_edit_modal');
Route::post('/profile-update/{id}', 'StaffController@profile_update')->name('profile.update');





Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/advance/search', 'AdvanceSearchController@index')->name('advance/search');
    Route::get('/bare_acts', 'BareActsController@index')->name('bare_acts');
    Route::get('/archive', 'ArchiveController@index')->name('archive');
    Route::get('/display_board', 'DisplayboardController@index')->name('display_board');
    Route::get('/court_fee_cal', 'CourtFeeController@index')->name('court_fee_cal');
    Route::get('/connected_matters', 'ConnectedMatersController@index')->name('connected_matters');
    Route::get('/my_client', 'MyclientController@index')->name('my_client');
    Route::get('case/active', 'CaseController@indexx')->name('case.active');
    Route::get('court_list', 'CourtListController@index')->name('court_list');
    Route::get('calculation', 'CalculationController@index')->name('calculation');
    Route::get('calculation_of_int', 'CalculationOfInterestController@index')->name('calculation_of_int');
    Route::get('ocr', 'OcrController@index')->name('ocr');
    Route::get('case/today', 'CaseController@indexxx')->name('case.today');
    Route::get('case/tomorrow', 'CaseController@indexxxx')->name('case.tomorrow');
    Route::get('case/dailyboard/{date?}', 'CaseController@indexxxxx')->name('case.dailyboard');
    Route::get('case/dateawaited', 'CaseController@indexxxxxx')->name('case.dateawaited');
    Route::post('case/update', 'CaseController@update')->name('case.update');

    Route::any('case/category/change/{id}', 'CaseController@category_change')->name('case.category.change');
    Route::any('case/category/store', 'CaseController@category_store')->name('case.category.store');

    Route::any('case/court/change/{id}', 'CaseController@court_change')->name('case.court.change');
    Route::any('case/court/store', 'CaseController@court_store')->name('case.court.store');

    Route::get('my-profile', 'StaffController@profile_view')->name('my-profile');
    Route::get('add-lawyer/{case}', 'CaseController@add_lawyer')->name('case.add_lawyer');
    Route::post('add-lawyer/{case}', 'CaseController@post_lawyer');
    Route::delete('remove-lawyer/{case}/{lawyer}', 'CaseController@remove_lawyer')->name('case.remove_lawyer');
    Route::post('update/next_date', 'CaseController@update_next_date')->name('update.next_date');

    Route::get('case_delete/{id}', 'CaseController@case_delete')->name('case.delete');

    Route::group(['middleware' => 'permission'], function () {

        Route::group(['prefix' => 'master', 'as' => 'master.', 'namespace' => 'Master'], function () {
            Route::resource('stage', 'StageController');
            Route::resource('act', 'ActController');
            Route::resource('court', 'CourtController');
        });


        Route::group(['prefix' => 'category', 'as' => 'category.', 'namespace' => 'Category'], function () {
            Route::resource('court', 'CourtController');
            Route::resource('case', 'CaseController');
            Route::resource('client', 'ClientController');
            Route::resource('contact', 'ContactController');
        });




        Route::resource('lawyer', 'LawyerController');

        Route::resource('contact', 'ContactController');

        Route::resource('client', 'ClientController');
        Route::get('case/filter', 'CaseController@filter')->name('case.filter');


        Route::resource('case', 'CaseController');

        Route::get('date/send_mail', 'HearingDateController@send_mail')->name('date.send_mail');
        Route::post('date/send_mail', 'HearingDateController@post_send_mail');
        Route::resource('date', 'HearingDateController');
        Route::resource('putlist', 'PutlistController');
        Route::resource('lobbying', 'LobbyingController');


        Route::any('judgement/reopen', 'JudgementController@reopen')->name('judgement.reopen');
        Route::any('judgement/close', 'JudgementController@close')->name('judgement.close');

        Route::get('/causelist', 'CaseController@causelist')->name('causelist.index');

        Route::any('closed', 'JudgementController@closed')->name('judgement.closed');

        Route::resource('judgement', 'JudgementController');

        Route::resource('appointment', 'AppointmentController');

        Route::any('judgement/reopen/store', 'JudgementController@reopen_store')->name('judgement.reopen_store');
        Route::any('judgement/close/store', 'JudgementController@close_store')->name('judgement.close_store');


        Route::get('/updateSystem', 'UpdateController@updatesystem')->name('setting.updatesystem');
        Route::post('/updateSystem', 'UpdateController@updatesystemsubmit')->name('setting.updateSystem.submit1');

        Route::group(['prefix' => 'setup', 'as' => 'setup.'], function () {
            Route::resource('country', 'CountryController');
            Route::resource('state', 'StateController');
            Route::resource('city', 'CityController');
        });

        Route::post('add/client', 'ClientController@store')->name('add.client');

        Route::post('add/organization', 'OrganizationController@store')->name('add.organization');
        Route::post('add/referance', 'OrganizationController@ref_store')->name('add.referance');

        Route::post('custom/district', 'CityController@custom_district')->name('custom_district');
        Route::post('custom/bench', 'CityController@bench')->name('bench');
        Route::post('custom/case_type', 'CityController@case_type')->name('case_type');

    });



    Route::get('/change-password', 'HomeController@change_password')->name('change_password');
    Route::post('/change-password', 'HomeController@post_change_password');

    Route::post('/search', 'SearchController@search')->name('search');

    Route::resource('file', 'FileController');
});


Route::any('date-reminder-corn', 'DateRemainderController@dueDate')->name('date-reminder');

Route::group(['as' => 'select.', 'prefix' => 'select'], function () {
    Route::get('/division', 'Api\SelectController@division')->name('division');
    Route::post('/state', 'Api\SelectController@state')->name('state');
    Route::post('/city', 'Api\SelectController@city')->name('city');
    Route::post('/court', 'Api\SelectController@court')->name('court');
});



Route::get('/js/lang/js', function () {

    //    if (\App::environment('local')) {
    \Cache::forget('jslang.js');
    //    }

    if (\Cache::has('locale')) {
        config(['app.locale' => \Cache::get('locale')]);
    }

    $strings = Cache::rememberForever('jslang.js', function () {
        $lang = config('app.locale');

        $file   = resource_path('lang/' . $lang . '/js.php');
        $strings = [];
        if (\Illuminate\Support\Facades\File::exists($file)) {
            $name           = basename($file, '.php');
            $strings[$name] = require $file;
        }

        //        Remove this if block if you dont need to load language insides module

        if (class_exists(\Nwidart\Modules\Module::class)) {
            $modules = \Module::all();
            $module_files = [];
            foreach ($modules as $module) {
                if ($module->isEnabled()) {
                    $file = module_path($module->getName()) . '/Resources/lang/' . $lang . '/js.php';
                    if (\Illuminate\Support\Facades\File::exists($file)) {
                        $module_files[$module->getLowerName()] = $file;
                    }
                }
            }

            foreach ($module_files as $module => $file) {
                $name           = basename($file, '.php');
                $strings[$module . '::' . $name] = require $file;
            }
        }

        return $strings;
    });
    header('Content-Type: text/javascript');
    echo ('window.jsi18n = ' . json_encode($strings) . ';');
    exit();
})->name('assets.lang.js');

app/Http/Controllers/LobbyingController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cases;
use App\Models\HearingDate;
use App\Traits\CustomFields;
use App\Traits\ImageStore;
use Illuminate\Http\Request;
use Illuminate\Validation\ValidationException;

class LobbyingController extends Controller
{
    use ImageStore, CustomFields;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $date = date("m/d/Y");
        if ($request->date) {
            $date = getFormatedDate($request->date, true);
        }
        $case_id = [];

        $models = HearingDate::with('cases')->whereDate('date', $date)->where('type', 'lobbying')->whereNull('status')->get();
        return view('lobbying.index', compact('models', 'date'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        if (!$request->case) {
            abort(404);
        }
        $case = $request->case;
        $fields = null;

        if (moduleStatusCheck('CustomField')){
            $fields = getFieldByType('lobbying_date');
        }
        $case_model = Cases::findOrFail($case);
        return view('lobbying.create', compact('case', 'case_model', 'fields'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (!$request->json()) {
            abort(404);
        }

        $validate_rules = [
            'hearing_date' => 'required|date',
            'description' => 'required|string',
            'file.*' => 'sometimes|nullable|mimes:jpg,bmp,png,doc,docx,pdf,jpeg,txt',
        ];
        if (moduleStatusCheck('CustomField')){
            $validate_rules = array_merge($validate_rules, $this->generateValidateRules('lobbying_date'));
        }
        $request->validate($validate_rules, validationMessage($validate_rules));

        $case = Cases::find($request->case);
        if (!$case) {
            throw ValidationException::withMessages(['hearing_date' => __('case.Case Not Found')]);
        }


        $model = new HearingDate();
        $model->cases_id = $request->case;
        $model->date = getFormatedDate($request->hearing_date);
        $model->description = $request->description;
        $model->type = 'lobbying';
        $model->save();
        if (moduleStatusCheck('CustomField')){
            $this->storeFields($model, $request->custom_field, 'lobbying_date');
        }
        if ($request->file){
            foreach($request->file as $file){
                $this->storeFile($file, $model->cases_id, $model->id);
            }
        }
        $response = [
            'goto' => route('case.show', $model->cases_id),
            'model' => $model,
            'message' => __('case.Date Added Successfully'),
        ];

        return response()->json($response);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $id)
    {
        if (!$request->case) {
            abort(404);
        }
        $case = $request->case;
        $date = HearingDate::where(['cases_id' => $case, 'id' => $id, 'type' => 'lobbying'])->firstOrFail();
        $model = Cases::findOrFail($case);
        return view('lobbying.show', compact('case', 'model','date'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        if (!$request->case) {
            abort(404);
        }
        $case = $request->case;

        $model = HearingDate::where(['cases_id' => $case, 'id' => $id, 'type' => 'lobbying'])->firstOrFail();
        $case_model = Cases::findOrFail($case);
        $fields = null;

        if (moduleStatusCheck('CustomField')){
            $fields = getFieldByType('lobbying_date');
        }
        return view('lobbying.edit', compact('case', 'model', 'case_model', 'fields'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (!$request->json()) {
            abort(404);
        }

        if (!$request->json()) {
            abort(404);
        }
        $validate_rules = [
            'hearing_date' => 'required|date',
            'description' => 'required|string',
        ];
        if (moduleStatusCheck('CustomField')){
            $validate_rules = array_merge($validate_rules, $this->generateValidateRules('lobbying_date'));
        }
        $request->validate($validate_rules, validationMessage($validate_rules));
        $case = Cases::find($request->case);
        $model = HearingDate::find($id);

        if (!$case) {
            throw ValidationException::withMessages(['hearing_date' => __('case.Case Not Found')]);
        }
        $hearing_date = HearingDate::where('type', 'lobbying')->where('cases_id', $request->case)->latest()->first();

        if (strtotime($hearing_date->date) > strtotime($request->hearing_date)) {
            throw ValidationException::withMessages(['hearing_date' => __('case.New Date Must be after') . $hearing_date->date]);
        }

        $model->cases_id = $request->case;
        $model->date = getFormatedDate($request->hearing_date);
        $model->description = $request->description;
        $model->status = $request->status;
        $model->save();
        if (moduleStatusCheck('CustomField')){
            $this->storeFields($model, $request->custom_field, 'lobbying_date');
        }
        $response = [
            'goto' => route('case.show', $model->cases_id),
            'message' => __('case.Date Updated Successfully'),
        ];

        return response()->json($response);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        if (!$request->json()) {
            abort(404);
        }

        $model = HearingDate::where('type', 'lobbying')->find($id);

        if (!$model) {
            throw ValidationException::withMessages(['message' => __('case.Case Not Found')]);
        }
        if (moduleStatusCheck('CustomField')){
            $model->load('customFields');
            $model->customFields()->delete();
        }

        $model->delete();

        return response()->json(['message' => __('case.Date Deleted Successfully'), 'goto' => route('case.show', $model->cases_id)]);
    }
}

resources/views/lobbying/index.blade.php
@extends('layouts.master', ['title' => __('case.Lobbying')])

@section('mainContent')

<section class="admin-visitor-area up_st_admin_visitor">
        <div class="container-fluid p-0">
            <div class="row justify-content-center">
                <div class="col-12">
                    <div class="box_header common_table_header">
                        <div class="main-title d-md-flex">
                            <h3 class="mb-0 mr-30 mb_xs_15px mb_sm_20px">{{ __('case.Lobbying List')}} | {{ __('case.Date')}} :{{formatDate($date) }}</h3>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12 mb-3">
                    <div class="white_box_50px box_shadow_white">

                        {!! Form::open(['route' => 'lobbying.index', 'method' => 'get']) !!}

                            <div class="row">
                                <div class="col">
                                    <div class="primary_input mb-15">
                                        <label class="primary_input_label" for="">{{ __('common.Date From') }}</label>
                                        <div class="primary_datepicker_input">
                                            <div class="no-gutters input-right-icon">
                                                <div class="col">
                                                    <div class="">
                                                    {{Form::text('date', date('Y-m-d'), ['class' => 'primary_input_field primary-input date form-control', "id"=>"fromDate",'placeholder' => __('common.Date')])}}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col mt-4">
                                    <div class="primary_input mt-3">
                                        <button type="submit" class="primary-btn fix-gr-bg" id="submit" value="submit" style="width: 100%;"><i class="ti-search"></i>{{ __('common.Get List') }}</button>
                                    </div>
                                </div>
                            </div>
                            {!! Form::close() !!}
                    </div>
                </div>
                <div class="col-12 mt-15">
                        <div class="box_header common_table_header">
                            <div class="main-title d-md-flex">
                                <h3 class="mb-0 mr-30 mb_xs_15px mb_sm_20px">{{__('case.Lobbying')}}</h3>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="QA_section QA_section_heading_custom check_box_table">
                            <div class="QA_table ">
                                <div class="">
                                <table class="table Crm_table_active3">
                                    <thead>
                                        <tr>
                                            <th scope="col">{{ __('common.SL') }}</th>
                                            <th>{{ __('case.Case') }}</th>
                                            <th>{{ __('case.Client') }}</th>
                                            <th>{{ __('case.Details') }}</th>
                                            <th>{{ __('case.Date') }}</th>
                                            <th>{{ __('case.Status') }}</th>
                                            <th class="noprint">{{ __('common.Actions') }}</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($models as $model)
                                        <tr>
                                            <td>{{ $loop->index + 1 }}</td>
                                            <td>
                                                <b>{{ __('case.Case No') }}: </b>
                                                {{$model->cases->case_category? $model->cases->case_category->name : '' }}/{{$model->cases->case_no}}
                                                <br>
                                                <a href="{{route('category.case.show', $model->cases->case_category_id)}}"><b>{{ __('case.Category') }}:
                                                    </b> {{$model->cases->case_category? $model->cases->case_category->name : '' }}</a>
                                                <br>
                                                <a href="{{ route('case.show', $model->cases->id) }}"><b>{{ __('case.Case No') }}{{ __('case.Title') }}:
                                                    </b>{{ $model->cases->title }}
                                                </a>
                                                <br>
                                                <b>{{ __('case.Next Hearing Date') }}: </b> {{ formatDate($model->cases->hearing_date) }} <br>
                                                <b>{{ __('case.Filing Date') }}: </b> {{ formatDate($model->cases->filling_date) }}
                                            </td>
                                            <td>
                                                @if($model->cases->client == 'Plaintiff' and $model->cases->plaintiff_client)
                                                <a href="{{route('client.show', $model->cases->plaintiff_client->id)}}"><b>{{ __('case.Name') }}</b>:
                                                    {{ $model->cases->plaintiff_client->name }}</a> <br>
                                                <b>{{ __('case.Mobile') }}: </b> {{ $model->cases->plaintiff_client->mobile }} <br>
                                                <b>{{ __('case.Email') }}: </b> {{ $model->cases->plaintiff_client->email }} <br>
                                                <b>{{ __('case.Address') }}: </b> {{ $model->cases->plaintiff_client->address }}
                                                {{ $model->cases->plaintiff_client->city ? ', '. $model->cases->plaintiff_client->city->name : '' }}
                                                {{ $model->cases->plaintiff_client->state ? ', '. $model->cases->plaintiff_client->state->name : '' }}
                                                @elseif($model->cases->client == 'Opposite' and $model->cases->opposite_client)
                                                <a href="{{route('client.show', $model->cases->opposite_client->id)}}"><b>{{ __('case.Name') }}</b>:
                                                    {{ $model->cases->opposite_client->name }}</a> <br>
                                                <b>{{ __('case.Mobile') }}: </b> {{ $model->cases->opposite_client->mobile }} <br>
                                                <b>{{ __('case.Email') }}: </b> {{ $model->cases->opposite_client->email }} <br>
                                                <b>{{ __('case.Address') }}: </b> {{ $model->cases->opposite_client->address }}
                                                {{ $model->cases->opposite_client->city ? ', '. $model->cases->opposite_client->city->name : '' }}
                                                {{ $model->cases->opposite_client->state ? ', '. $model->cases->opposite_client->state->name : '' }}
                                                @endif
                                            </td>
                                            <td>
                                                @if($model->cases->court)
                                                <a href="{{route('master.court.show', $model->cases->court_id)}}"><b>{{ __('case.Court') }}</b>:
                                                    {{ $model->cases->court->name}} </a><br>
                                                <a href="{{route('category.court.show', $model->cases->court_category_id)}}">
                                                    <b>{{ __('case.Category') }}</b>:
                                                    {{ $model->cases->court->court_category ? $model->cases->court->court_category->name : '' }}
                                                </a><br>
                                                <b>{{ __('case.Room No') }}: </b> {{ $model->cases->court->room_number }} <br>
                                                <b>{{ __('case.Address') }}: </b> {{ $model->cases->court->location }}
                                                {{ $model->cases->court->city ? ', '. $model->cases->court->city->name : '' }}
                                                {{ $model->cases->court->state ? ', '. $model->cases->court->state->name : '' }}
                                                @endif
                                            </td>
                                            <td>
                                                {{formatDate($model->date)}}
                                            </td>
                                            <td>
                                            {!! $model->status ? '<span class="badge_1"> Complete </span>' : '<span class="badge_4"> Incomplete </span>' !!}

                                            </td>

                                            <td>


                                                <div class="dropdown CRM_dropdown">
                                                        <button class="btn btn-secondary dropdown-toggle" type="button"
                                                                id="dropdownMenu2" data-toggle="dropdown"
                                                                aria-haspopup="true"
                                                                aria-expanded="false">
                                                            {{ __('common.Select') }}
                                                        </button>
                                                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu2">

                                                        <a href="{{route('lobbying.show', [$model->id, 'case' => $model->cases_id])}}" class="dropdown-item"><i
                                                                class="icon-file-eye"></i> {{ __('common.View') }}</a>
                                                        @if(!$model->judgement)
                                                            @if(permissionCheck('lobbying.edit'))
                                                            <a href="{{route('lobbying.edit', [$model->id, 'case' => $model->cases_id])}}"
                                                                class="dropdown-item"><i
                                                                    class="icon-pencil mr-2"></i>{{ __('common.Edit') }}</a>
                                                            @endif
                                                            @if(permissionCheck('lobbying.destroy'))
                                                            <a data-url="{{route('lobbying.destroy', $model->id)}}"
                                                                class="dropdown-item" id="delete_item"><i
                                                                    class="icon-trash mr-2"></i>{{ __('common.Delete') }}</a>
                                                            @endif
                                                        @endif
                                                        </div>
                                                    </div>


                                            </td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
    </section>


@stop
@push('admin.scripts')

<script>
    $(document).ready(function () {


    });

</script>

@endpush